### ISSUE TITLE
[BUG] Invoke-mimikatz can not DumpCerts

### ISSUE THREAD

**Issue by dickens88** [BC-SECURITY/Empire#134]
**Empire Version**
- Empire 3.x latest version

**OS Information (Linux flavor, Python version)**
- OS: win10 1903 18362.720
- Python: no

**Describe the bug**
I'm trying to use DumpCerts at win10 1903 os, but got issue, showing below:

ERROR kuhl_m_sekurlsa_acquireLSA ; Handle on memory (0x00000005)

**To Reproduce**
1. Go to '. .\Invoke-Mimikatz.ps1'
2. Click on 'Invoke-Mimikatz -DumpCreds'

**Expected behavior**
I'm trying to use DumpCerts at win10 1903 os, but got issue, showing below:

ERROR kuhl_m_sekurlsa_acquireLSA ; Handle on memory (0x00000005)

**Screenshots**

![sc2020-03-190008](https://user-images.githubusercontent.com/8390209/77031411-7e3efc00-69dc-11ea-88d1-de846928167d.png)

**Additional context**

**Comment by Cx01N** [comment]
@dickens88 What version of empire are you running? It looks like you are running mimikatz directly from the script without Empire.

**Comment by dickens88** [comment]
@Cx01N hi, in fact, i run the invoke-mimikatz script which is in the Empire project directly. https://github.com/BC-SECURITY/Empire/blob/master/data/module_source/credentials/Invoke-Mimikatz.ps1

i download the latest version just now. Do i need to change another way?

**Comment by Cx01N** [comment]
@dickens88 can you provide steps and a screenshot? The one you provided is of mimikatz being ran directly on a target without the use of Empire.

In the future, please fill out the Empire version number, Python version, and Linux flavor to ensure we can answer any questions quickly.

I also suggest opening a ticket on their github due to this appearing to be a Mimikatz error and not Empire.

**Comment by dickens88** [comment]
@Cx01N ok sure, i will follow your suggestion, thank you very much
