### ISSUE TITLE
Question about new ways of bypassing WindowsDefender

### ISSUE THREAD

**Issue by whmacmac** [BC-SECURITY/Empire#170]
## Empire Version
3.1.4

## OS Information (Linux flavor, Python version)
5.4.0-4parrot1-amd64 #1 SMP Parrot 5.4.19-4parrot1 (2020-02-27) x86_64 GNU/Linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Hi, I watched your presentation about AMSI bypass and sandboxing. My bad was that i waited till today to test what i learnt from you guys. I mixed the obfuscation methods like hell with the hope to bypass Windows Defender but with no success, i also enabled all checking and amsi bypassing features but with no success. 
My question is the following, i would love to start taking looking for ways to bypass it but i ask you from where to start? From what i observed, the first stager is caught. Should I look at the AmsiBypass script that is added at our stager? I am curious about this and how should i try to improve the Windows evasion. The intro was not enough and my curiosity is harder to support than in the past. Please let me know for tips and which functions should i look first for improving the Empire project. 

## Any additional information
Tried the following combinations of obfuscation:
Token\All\1, Ast\All\1, Compress\1
Encoding\Secure\1, Token\All\1, Compress\1
Encoding\Secure\1, Token\All\1

I observed that everytime Windows Defender is asking me if i want to upload the file in their cloud for finding out if the script is malicious or not ... So i suppose a little part of it, is flagged by AMSI but not sure which one. Looking forward for your response. Thanks.

PS: I found this: https://github.com/BC-SECURITY/Empire/blob/master/lib/common/bypasses.py . Should i focus only on this for seeing if Microsoft is managing to catch me through this and trying to optimize it or should i look to somewhere else too?

**Comment by Hubbl3** [comment]
@whmacmac  I am going to close this issue because it's not really relevant to the development of Empire. In the future the bloodhound gang has a slack channel on their server that's dedicated to Empire that I hang out in and can help you there.

For now, here are some tips:

First turn safechecks off. I need to rename it but safechecks really just checks if the version is powershell 3 or higher is being used as part of the signature.

Turn base64 off. It doesn't add anything to your obfuscation while trying to avoid defender. It's really just used because it's the easiest way to handle sending the command in a string. Once you have your obfuscated code you can re-encode it. 

The order of functions is a really big way that AMSI is fingerprinting now. There are number of position independent commands you cna move around to break the signature. 

Finally, any of the \all options in Invoke-Obfuscation is likely to get caught try using a custom combination of the sub options.

**Comment by Hubbl3** [comment]
Also here is a really good article on AMSI Bypasses 

https://modexp.wordpress.com/2019/06/03/disable-amsi-wldp-dotnet/
