### ISSUE TITLE
[BUG] slack token error when agent connected

### ISSUE THREAD

**Issue by ghost5egy** [BC-SECURITY/Empire#181]
**Empire Version**
- Empire 3.x

**OS Information (Linux flavor, Python version)**
- OS: debian
- Python: 3

**Describe the bug**
I got this message when agent register on empire if I set the slack token :
TypeError: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.

the I lose the agent it goes to loop  trying to register vise versa
**To Reproduce**

**Expected behavior**
I think it's caused because of shifting from python 2 to python3 .

**Screenshots**
none
**Additional context**
nope

**Comment by Cx01N** [comment]
@ghost5egy We must have missed a few lines during the python3 conversion. I will see about getting this fixed in a future release. We also take PRs if you think you can fix it. Thanks.

**Comment by Cx01N** [comment]
@ghost5egy @Gl3bGl4z 
I fixed the slack encoding issue, however, it looks like slack is dropping legacy API support and will discontinue token creation on May 5th. I recommend getting a new token ASAP before they drop that functionality. Especially since it may be some time before we update the slack functionality to work with the newer API.
