### ISSUE TITLE
Gives this error: ModuleNotFoundError: No module named '_sqlite3', when I try to run empire

### ISSUE THREAD

**Issue by NonsoEchendu** [BC-SECURITY/Empire#212]
## Empire Version
3.2.1

## OS Information (Linux flavor, Python version)
Kali Linux 2020.2

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Installation caught a few errors: 
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
ERROR: Could not find a version that satisfies the requirement urllib3 (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for urllib3 (from -r requirements.txt (line 1))

Goes on to complete setup, though. Then when i try to run empire, it says no module named sqlite3.
Will attach a screenshot of it to be clear.

## Screenshot of error, embedded text output, or Pastebin link to the error
Errors during installation:
https://ibb.co/02tpShs

Error while trying to run:
https://ibb.co/F4WsmYr

**Comment by Cx01N** [comment]
@NonsoEchendu You are getting a connection failed at the beginning. It looks like you don't have access to the internet on your machine. You will need to bridge your Kali VM to install the dependencies. Let us know if that fixes the issue.

**Comment by NonsoEchendu** [comment]
I have very good internet access.

**Comment by NonsoEchendu** [comment]
> @NonsoEchendu You are getting a connection failed at the beginning. It looks like you don't have access to the internet on your machine. You will need to bridge your Kali VM to install the dependencies. Let us know if that fixes the issue

My Kali's internet isn't a problem

**Comment by Hubbl3** [comment]
@NonsoEchendu if you haven't already try running `sudo apt update` and then `sudo apt upgrade`

I just tried installing on a new Kali 2020.2 install and had no issues. You can also try installing through the package manager using ` sudo apt install powershell-empire`

If you still have issues can you please provide more details on how you installed Kali and if you have installed any other packages. For instance if you installed python 2.7 that may cause issues because the 2020 versions of Kali should have python 3 mapped to pip but installing 2.7 could override that

**Comment by NonsoEchendu** [comment]
@Hubbl3 Thanks so much man. re-ran the sudo apt update and sudo apt upgrade. (though i had done it before). Then i used the sudo apt install powershell-empire, instead of git cloning and installing from the folder.
Worked immediately. Thanks so very much, i appreciate
