### ISSUE TITLE
[FEATURE REQUEST] Trouble with uploads in RESTful API

### ISSUE THREAD

**Issue by fm1ck3y** [BC-SECURITY/Empire#378]
##  Is your feature request related to a problem? Please describe.
I am trying to upload a file to the agent using RESTful API, every time I try to do it, I just don't get the file loaded. 

## Describe the solution you'd like
I want to upload a file to an agent using RESTful API

## Describe alternatives you've considered
-

## Additional context
I apologize in advance, I do not know where to write to.
this my get request
![code](https://user-images.githubusercontent.com/34456690/97479084-e5556380-1962-11eb-83d8-b5f266fe4dd2.png)

**Comment by Cx01N** [comment]
@fm1ck3y In the future, please open issues if you are having a problem or ask for assistance on your [Discord](https://discord.com/invite/P8PZPyf). We will need a bit more information to help you out, but I highly encourage getting in our channel if you are trying to code your own API client since that doesn't fall as a feature request or bug.
