### ISSUE TITLE
[BUG] Shell output missing carriage returns for various commands

### ISSUE THREAD

**Issue by spookymonkey2020** [BC-SECURITY/Empire#491]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.1.2

## OS Information (Linux flavor, Python version)
- OS: Kali
- Python: 3.9

## Describe the bug
Shell output missing carriage returns for various commands, which makes reading output extremely difficult.

## To Reproduce
1. Open shell with 'shell' command
2. Issue following command: schtasks /query /fo LIST /v
3. Notice output is jumbled and appears to be missing carriage returns.
4. Next type command: tree c:\Users /a /f
5. Then try this command: netsh firewall show state

## Expected behavior
Carriage returns/line breaks should be observed in the output, producing much more user-friendly output.

## Screenshots
![image](https://user-images.githubusercontent.com/88156271/135548687-ff187db0-b822-44dc-8355-319c3d76057e.png)

![image](https://user-images.githubusercontent.com/88156271/135548671-64f0ac11-a5d4-4114-ad56-bfdd1dbdeaf6.png)

## Additional context
N/A

**Comment by Cx01N** [comment]
@spookymonkey2020 Thanks for pointing this one out. I'm pretty stumped on what is causing it on some responses and not others. I don't want to force all commands to format a certain way because that may have some other issues down the road. For now, if you add `| convertto-json` to the end of those they will come back with a formatted response that is readable. I'll see if I can come up with a fix in the future, but at least this will get you a result that isn't a wall of text.

**Comment by vinnybod** [comment]
This was fixed by https://github.com/BC-SECURITY/Empire/pull/526 and will be in the 4.3.1 release. I tested it with the example commands in the original post.

**Comment by spookymonkey2020** [comment]
Thanks to everyone involved for your work on this issue and the broader project as a whole!!!
