### ISSUE TITLE
[BUG] urllib3 cant import

### ISSUE THREAD

**Issue by stx86** [BC-SECURITY/Empire#515]
![Screenshot_2021-11-14_07_31_58](https://user-images.githubusercontent.com/90972298/141681433-7f85fb63-66f4-4886-8e97-77102ccb1bb9.png)
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 3.x

## OS Information (Linux flavor, Python version)
- OS: 
- Python: 

## Additional context

Why do i get this? The urllib3 is there?
I have tryied to change to import it but get same faults. 

When i changed if args.subparser_name == 'server':
TO if args.subparser_name == 'server.py':

It run and nothing was shown. I cant figure it out. Any solution to this?

Traceback (most recent call last):
  File "/home/kali/tools/Empire/empire.py", line 11, in <module>
    import empire.server.server as server
  File "/home/kali/tools/Empire/empire/server/server.py", line 21, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'

**Comment by Cx01N** [comment]
Please fill out the rest of the form and provide additional info.

**Comment by adamczi** [comment]
I also experienced the same issue on latest v4.2.0, new install on a fresh Ubuntu. Somehow I managed to run it by trying each installation step with and without `sudo`, I can't remember what exactly solved it.

Related: I think the docs are inconsistent about how to run Empire - quickstart on wiki says to run `sudo poetry run python empire.py server` whereas quickstart on project's main page here says `poetry run python empire.py server`. It would be good to clarify it because the wiki also instructs to install Empire with `sudo poetry install`.

**Comment by Cx01N** [comment]
@adamczi thanks for the heads up. I'll get that updated so it's less confusing.

Also, if you could provide more info on how you came across the same issue and fixed it that would be helpful. I haven't been able to recreate it.

**Comment by sdcampbell** [comment]
I'm getting the same error on Empire-Sponsors. I found that the installation works and I don't get an error if I answer no to "want to install xar and bomutils", then it completes the installation and everything works. I'm on the latest version of Kali.

**Comment by Cx01N** [comment]
@sdcampbell I think the install script was failing on this package for some people and that's why they are getting urllib3 not found. I was able to get the bomutils error on a brand new box, can you test out installing it again? And swap out this line https://github.com/BC-SECURITY/Empire/blob/6d8169a8ea818f9af478e173a9a548c626c80d05/setup/install.sh#L44
with `git clone https://github.com/Cx01N/bomutils.git` and see if it is successful. I'm hoping it works for more than just me.

**Comment by Cx01N** [comment]
This should be resolved now with the changes merged into bomutils. But if its still causing issues, please let us know and we can reopen the issue.
