### ISSUE TITLE
[BUG] delete the results buffer for a single agent not working as expected

### ISSUE THREAD

**Issue by havocsh** [BC-SECURITY/Empire#535]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.3.3

## OS Information (Linux flavor, Python version)
- OS: Ubuntu Linux
- Python: 3.8

## Describe the bug
Trying to delete the results buffer for a single agent via the API as described here does not work: https://bc-security.gitbook.io/empire-wiki/restful-api/agents#delete-agent-results
Executing the command returns "success" but the agent shell command results buffer still holds previous shell command results.

## To Reproduce
1. Launch an agent and run some shell commands through it.
2. Use the GET /api/agents/AGENT_NAME/results handler to view the results from the shell command.
3. Use the DELETE /api/agents/AGENT_NAME/results handler to clear the agent shell command results buffer.
4. Use the GET /api/agents/AGENT_NAME/results handler again.

## Expected behavior
The results buffer should be empty when querying it after running the DELETE command but it is not.

## Screenshots
No screenshots were taken.

## Additional context
No other context to add.

**Comment by vinnybod** [comment]
This endpoint doesn't really do anything as of sometime in Empire 4, when we moved to the server/client architecture.

In Empire <4, when taskings came back, in addition to the results being stored in the `Taskings` table, it would append the results to the `results` column on the `Agents` table. This would stay here until the user viewed the buffer, at which point it would be cleared. Or a REST call to the endpoint could preemptively clear it via `DELETE /api/agents/AGENT_NAME/results`

After separating out the client and moving to a multi-user approach, this didn't really work because different users might be viewing results for the same agents. So the idea of the server-side buffer was removed, instead, the individual clients have their own results buffer that they store when tasks are completed.

`GET /api/agents/<string:agent_name>/results`
This endpoint gets all the taskings for an agent (not the buffer). No amount of calls to clear the buffer will delete the taskings.

`/api/agents/<string:agent_name>/clear`
Currently, individual taskings cannot be deleted once they've been picked up by the agent. However, there is an endpoint to clear queued tasks.

Hope this makes sense.

**Comment by havocsh** [comment]
> This endpoint doesn't really do anything as of sometime in Empire 4, when we moved to the server/client architecture.
> 
> In Empire <4, when taskings came back, in addition to the results being stored in the `Taskings` table, it would append the results to the `results` column on the `Agents` table. This would stay here until the user viewed the buffer, at which point it would be cleared. Or a REST call to the endpoint could preemptively clear it via `DELETE /api/agents/AGENT_NAME/results`
> 
> After separating out the client and moving to a multi-user approach, this didn't really work because different users might be viewing results for the same agents. So the idea of the server-side buffer was removed, instead, the individual clients have their own results buffer that they store when tasks are completed.
> 
> `GET /api/agents/<string:agent_name>/results` This endpoint gets all the taskings for an agent (not the buffer). No amount of calls to clear the buffer will delete the taskings.
> 
> `/api/agents/<string:agent_name>/clear` Currently, individual taskings cannot be deleted once they've been picked up by the agent. However, there is an endpoint to clear queued tasks.
> 
> Hope this makes sense.

@vinnybod, thanks for the response. Yep, makes sense. I just realized that the taskings get a unique "taskID" and I should be using that to find the corresponding results. Suddenly the problem I'm trying to solve just got a whole lot easier. Thanks again for your help.
