### ISSUE TITLE
[BUG] Docker container maxing out CPU

### ISSUE THREAD

**Issue by 4kp3n** [BC-SECURITY/Empire#609]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.8.0

## OS Information (Linux flavor, Python version)
- OS: Arch Linux/ Kali Linux
- Python: 

## Describe the bug
When starting the empire docker container the CPU load for that process does not drop below 95% at any given time.
Also tested with older version (4.5.5), same issue.
Tested on both, an Arch Linux system with Kernel 5.19.5 and a Kali Linux with Kernel 5.18.0.

## To Reproduce
1. Clone newest image and run the empire server
```bash
docker run -it -p 1337:1337 -p 5000:5000 bcsecurity/empire:v4.8.0
```
2. Investigate CPU load of process

## Expected behavior
Docker container does not max out the CPU to 100%. 
(Running empire native on kali system doesn't)

## Screenshots
![_2022-09-01_19-09-1662053376](https://user-images.githubusercontent.com/19542827/187976621-99d5cf10-748f-4592-9b46-26c424229519.jpg)

**Comment by dwilson5** [comment]
I've run into this issue running empire natively in Kali.  I tracked down the issue to the `csharpserver.plugin`, and I'm curious if you're seeing the same thing.

When starting up the server, I get an error message just before the `Server >` prompt:

```
[*] Empire starting up...
[*] Starting Empire RESTful API on 0.0.0.0:1337
[*] Starting Empire SocketIO on 0.0.0.0:5000
[*] Testing APIs
[+] Empire RESTful API successfully started
[+] Empire SocketIO successfully started
[*] Cleaning up test user
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.String.ToLowerInvariant()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.GetArch()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment..cctor()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.GetRuntimeIdentifier()
   at Microsoft.DotNet.Cli.MulticoreJitProfilePathCalculator.CalculateProfileRootPath()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.StartCliProfileOptimization()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.TryActivateMulticoreJit()
   at Microsoft.DotNet.Cli.Program.Main(System.String[])
[+] Plugin csharpserver ran successfully!
Server >
```

Since the build of csharpserver failed, the output pipe is closed, causing the handling code to enter an infinite loop:

https://github.com/BC-SECURITY/Empire/blob/3f2ad6ad9a4f253c7c474e9aefeb6b66e0a0134d/empire/server/plugins/csharpserver.plugin#L133-L137

I fixed the CPU issue by checking that `output` has some content before calling `.rstrip()`, and exiting the thread if it doesn't:

```python
 def thread_csharp_responses(self):
     while True:
         output = self.csharpserver_proc.stdout.readline()
         if not output:
             return
         output = output.rstrip()
         if output:
             print(helpers.color("[*] " + output.decode("UTF-8")))
```

For personal awareness, I added in an extra `print(helpers.color("[!] csharpserver output stream closed"))` just before the return.

Getting C# server building and running is a separate issue; however, you can disable it and avoid this issue altogether by changing [this line](https://github.com/BC-SECURITY/Empire/blob/3f2ad6ad9a4f253c7c474e9aefeb6b66e0a0134d/empire/server/config.yaml#L25) in the server `config.yaml` to `status: stop`

**Comment by lavafroth** [comment]
Looks like this can be fixed by installing `libicu-dev`.
