### ISSUE TITLE
OSX Catalina - ModuleNotFoundError: No module named 'future'

### ISSUE THREAD

**Issue by benichmt1** [BC-SECURITY/Empire#81]
## Empire Version

3.0.5 (latest)

## OS Information (Linux flavor, Python version)

Host OS: Ubuntu 18.04, Python 3.6.9
Victim OS: OSX Catalina, Python 3.7.3

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

- Empire installed using `install.sh`. Pip and Pip3 both exist on the server. No errors during installation.
- Start Empire server (Ubuntu)
- Create http listener (configuring host IP, bind IP, and port)
- `usestager osx/launcher`
- `set SafeChecks false`
- `set Listener <myname>`
- `execute`; receive Python launcher code

## Screenshot of error, embedded text output, or Pastebin link to the error

On the victim machine after pasting in the launcher:
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 18, in <module>
  File "<string>", line 460, in <module>
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'future'
```

The Empire server shows an initial staging and then becomes stale. 

## Any additional information

I haven't had a chance to dig into this yet, will keep troubleshooting.

**Comment by vinnybod** [comment]
I tested this on Catalina and was able to successful connect the agent with an http listener and the osx/launcher stager:
Remove the future/builtin imports in [data/agent/stagers/http.py](https://github.com/BC-SECURITY/Empire/blob/master/data/agent/stagers/http.py) and [data/agent/agent.py](https://github.com/BC-SECURITY/Empire/blob/master/data/agent/agent.py). Since the stager seems to target python3 specifically, these are unnecessary.

Alternatively, if you have access to the machine, I believe you could pip install future.

In a future release we should probably remove `future` since it probably isn't reasonable to assume that the package would exist on the machine. But then that also has me wondering if we need a python 2.7 agent and a separate python3 agent.

**Comment by benichmt1** [comment]
> Remove the future/builtin imports in [data/agent/stagers/http.py](https://github.com/BC-SECURITY/Empire/blob/master/data/agent/stagers/http.py) and [data/agent/agent.py](https://github.com/BC-SECURITY/Empire/blob/master/data/agent/agent.py). Since the stager seems to target python3 specifically, these are unnecessary.

Removing all the future, builtin, standard_library, and past references was able to successfully stage an agent for me, thanks.
> 
> Alternatively, if you have access to the machine, I believe you could pip install future.

Because the intended purpose is creating a universal implant, I don't think that's the best idea.
> In a future release we should probably remove `future` since it probably isn't reasonable to assume that the package would exist on the machine. But then that also has me wondering if we need a python 2.7 agent and a separate python3 agent.

Interesting note here, it seems that scripting languages are potentially going to be deprecated in future versions of OSX... 
https://developer.apple.com/documentation/xcode_release_notes/xcode_11_release_notes?preferredLanguage=occ

**Comment by Cx01N** [comment]
We removed `import future` from v3.0.6. Please feel free to reopen if you run into a compatibility issue still.
